name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir -p site/${{ github.event.release.tag_name }}
          cp -r ru site/${{ github.event.release.tag_name }}/ru
          cp -r en site/${{ github.event.release.tag_name }}/en
          cp index.html site/${{ github.event.release.tag_name }}/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: true
          
